-- Enterprise Extensions Migration (Auth, Users, Notifications, Audit, Refresh Tokens)

CREATE TABLE IF NOT EXISTS refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token VARCHAR(255) NOT NULL UNIQUE,
    expiry_date TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS system_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    message TEXT NOT NULL,
    type VARCHAR(30) DEFAULT 'INFO' NOT NULL, -- INFO, SUCCESS, WARNING, ERROR
    is_read BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_login_activity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    ip_address VARCHAR(50),
    user_agent VARCHAR(255),
    login_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) NOT NULL
);

-- Seed Default Enterprise Users (Passwords: admin123, manager123, cashier123, kitchen123, inventory123, viewer123)
-- BCrypt encoded hash for 'admin123': $2a$10$e0MYzXyjpJS7Pd0RVvHwHe16n/G36m./o0WcT8x98e87vO3hL5V/O
INSERT INTO users (id, username, email, password_hash, full_name, role_id, status) VALUES
(1, 'superadmin', 'superadmin@pubexchange.com', '$2a$10$e0MYzXyjpJS7Pd0RVvHwHe16n/G36m./o0WcT8x98e87vO3hL5V/O', 'Super Administrator', 1, 'ACTIVE'),
(2, 'admin', 'admin@pubexchange.com', '$2a$10$e0MYzXyjpJS7Pd0RVvHwHe16n/G36m./o0WcT8x98e87vO3hL5V/O', 'System Administrator', 1, 'ACTIVE'),
(3, 'manager', 'manager@pubexchange.com', '$2a$10$e0MYzXyjpJS7Pd0RVvHwHe16n/G36m./o0WcT8x98e87vO3hL5V/O', 'Operations Manager', 3, 'ACTIVE'),
(4, 'cashier', 'cashier@pubexchange.com', '$2a$10$e0MYzXyjpJS7Pd0RVvHwHe16n/G36m./o0WcT8x98e87vO3hL5V/O', 'POS Cashier', 4, 'ACTIVE'),
(5, 'kitchen', 'kitchen@pubexchange.com', '$2a$10$e0MYzXyjpJS7Pd0RVvHwHe16n/G36m./o0WcT8x98e87vO3hL5V/O', 'Kitchen Staff', 3, 'ACTIVE'),
(6, 'inventory', 'inventory@pubexchange.com', '$2a$10$e0MYzXyjpJS7Pd0RVvHwHe16n/G36m./o0WcT8x98e87vO3hL5V/O', 'Inventory Manager', 3, 'ACTIVE'),
(7, 'viewer', 'viewer@pubexchange.com', '$2a$10$e0MYzXyjpJS7Pd0RVvHwHe16n/G36m./o0WcT8x98e87vO3hL5V/O', 'Executive Viewer', 5, 'ACTIVE');

-- Initial Notifications
INSERT INTO system_notifications (title, message, type) VALUES
('System Architecture Active', 'Enterprise Clean Architecture backend running with Spring Boot 3.3 and Java 21.', 'SUCCESS'),
('Dynamic Pricing Engine Ready', 'Real-time order velocity & stock pressure scoring active.', 'INFO');
