-- Core schema initialization

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    flavour VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255),
    default_cup_size_ml INT NOT NULL DEFAULT 250,
    default_cup_price DECIMAL(10, 2) NOT NULL DEFAULT 20.00,
    current_cup_price DECIMAL(10, 2) NOT NULL DEFAULT 20.00,
    min_cup_price DECIMAL(10, 2) NOT NULL DEFAULT 18.00,
    max_cup_price DECIMAL(10, 2) NOT NULL DEFAULT 25.00,
    last_price_change_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sales_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR(50) NOT NULL UNIQUE,
    total_amount DECIMAL(10, 2) NOT NULL,
    payment_method VARCHAR(20) NOT NULL,
    payment_status VARCHAR(20) NOT NULL DEFAULT 'COMPLETED',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sales_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    product_name VARCHAR(100) NOT NULL,
    cup_size_ml INT NOT NULL,
    unit_price DECIMAL(10, 2) NOT NULL,
    quantity INT NOT NULL,
    total_price DECIMAL(10, 2) NOT NULL,
    volume_deducted_ml INT NOT NULL,
    FOREIGN KEY (order_id) REFERENCES sales_orders(id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE inventory_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    batch_id BIGINT,
    transaction_type VARCHAR(50) NOT NULL,
    volume_change_ml INT NOT NULL,
    notes VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE price_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    old_price DECIMAL(10, 2) NOT NULL,
    new_price DECIMAL(10, 2) NOT NULL,
    demand_score DOUBLE PRECISION NOT NULL,
    stock_pressure_pct DOUBLE PRECISION NOT NULL,
    time_factor_multiplier DOUBLE PRECISION NOT NULL,
    explanation TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE system_config (
    config_key VARCHAR(100) PRIMARY KEY,
    config_value VARCHAR(255) NOT NULL,
    description VARCHAR(255)
);

-- Insert Default Config
INSERT INTO system_config (config_key, config_value, description) VALUES
('weight_velocity', '0.40', 'Demand score velocity weight'),
('weight_stock_pressure', '0.40', 'Demand score stock pressure weight'),
('weight_time_factor', '0.20', 'Demand score time factor weight'),
('cooldown_minutes', '10', 'Price change cooldown in minutes'),
('evaluation_window_minutes', '5', 'Price evaluation window in minutes');
