-- Juice Batches migration tracking 20L containers and volume in ML

CREATE TABLE juice_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    batch_code VARCHAR(50) NOT NULL UNIQUE,
    container_capacity_ml INT NOT NULL DEFAULT 20000,
    initial_volume_ml INT NOT NULL DEFAULT 20000,
    remaining_volume_ml INT NOT NULL DEFAULT 20000,
    cup_size_ml INT NOT NULL DEFAULT 250,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (product_id) REFERENCES products(id)
);
